version: "3.8"

volumes:
  database:
  es_data: {}
services:
  database:
    image: library/postgres:14-alpine
    container_name: docker-django-database
    restart: on-failure
    env_file:
      - env/database.env
    expose:
      - 5432
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]  # TODO: find a way to dynamically get the username
      interval: 10s
      timeout: 5s
      retries: 5
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: es
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  web:
    build: .
    container_name: web
    image: docker-django-app
    command:
      - /bin/sh
      - -c
      - |
        python manage.py compilemessages
        python manage.py migrate
        python manage.py collectstatic --noinput
        bash runserver.sh
    volumes:
      - .:/code
    expose:
      - 8081
      - 6800
    env_file:
      - env/app.env
      - env/database.env
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    links:
      - database

  nginx:
    image: library/nginx:latest
    container_name: docker-django-nginx
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    depends_on:
      - web
