# Generated by Django 4.1.7 on 2023-03-27 19:26

from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=512)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata", django_jsonform.models.fields.JSONField()),
                (
                    "collection",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="combio_app.collection"),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
