# Generated by Django 4.1.7 on 2023-03-27 16:39

import combio_app.models
from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("combio_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="metadata",
            field=django_jsonform.models.fields.JSONField(default=combio_app.models.get_default_data),
        ),
    ]
