# Generated by Django 4.1.7 on 2023-03-27 16:55

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("combio_app", "0002_alter_record_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="metadata",
            field=django_jsonform.models.fields.JSONField(
                default={
                    "properties": {
                        "combio": {
                            "properties": {
                                "participants": {
                                    "items": {
                                        "properties": {
                                            "name": {"type": "string"},
                                            "role": {
                                                "enum": ["interviewer", "interviewee", "participant"],
                                                "type": "string",
                                            },
                                        },
                                        "type": "object",
                                    },
                                    "type": "array",
                                },
                                "title": {"type": "string"},
                                "transcript": {"type": "string"},
                            },
                            "type": "object",
                        },
                        "dc": {
                            "properties": {
                                "date": {"type": "date"},
                                "description": {"type": "string"},
                                "publisher": {"type": "string"},
                            },
                            "type": "object",
                        },
                    },
                    "title": "combio_metadata_scheme",
                    "type": "object",
                }
            ),
        ),
    ]
